#ifndef VCPU_VCPU_ERRORS_H
#define VCPU_VCPU_ERRORS_H

#define FILE_NAME_NOT_PASSED 111
#define MORE_ARG_COMMAND_LINE 112
#define FAILED_OPEN_FILE 113
#define F_ALLOCATE_MEMORY 114


#endif //VCPU_VCPU_ERRORS_H
